<?php

/**
 * @file
 * TrueFalse question type for quiz module
 *
 * Allows the creation of "True or False" questions
 */


use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function truefalse_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.block':
      return t('A question type for the quiz module. A simplified version of multichoice where "true" and "false" are the alternatives.');
    case 'system.modules_list':
      return t('TrueFalse question type for the quiz module.');
    default:
      break;
  }
}

/**
 * Implements hook_quiz_question_config().
 */
function truefalse_quiz_question_config() {
  return FALSE;
}

/**
 * Implements hook_theme().
 */
/**
 * @todo Theming
function truefalse_theme() {
  return array(
    'truefalse_answering_form' => array(
      'render element' => 'form',
      'path' => drupal_get_path('module', 'truefalse') . '/theme',
      'template' => 'truefalse-answering-form',
    ),
    'truefalse_response' => array(
      'variables' => array(
        'metadata' => array(),
        'data' => array(),
      ),
    ),
  );
}
*/

/**
 * Theme the response part of the response report
 *
 * @param $metadata
 *  Can be used as a table header
 * @param $data
 *  Can be used as table rows
 */
function theme_truefalse_response($variables) {
  $metadata = $variables['metadata'];
  $data = $variables['data'];
  return theme('table', array('header' => $metadata, 'rows' => $data));
}
